Merancea/Controllers/ButtonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Merancea.Data;
using Merancea.Models;

namespace Merancea.Controllers
{
    public class ButtonsController : Controller
    {
        private readonly MeranceaContext _context;

        public ButtonsController(MeranceaContext context)
        {
            _context = context;
        }

        // GET: Buttons
        public async Task<IActionResult> Index()
        {
            var meranceaContext = _context.Buttons.Include(b => b.Page).Include(b => b.DestinationPage);
            return View(await meranceaContext.ToListAsync());
        }

        // GET: Buttons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Buttons == null)
            {
                return NotFound();
            }

            var button = await _context.Buttons
                .Include(b => b.Page)
                .Include(b => b.DestinationPage)
                .FirstOrDefaultAsync(m => m.ButtonId == id);
            if (button == null)
            {
                return NotFound();
            }

            return View(button);
        }

        // GET: Buttons/Create
        public IActionResult Create()
        {
            ViewData["PageId"] = new SelectList(_context.Pages, "Id", "Title");
            return View();
        }

        // POST: Buttons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ButtonId,Text,Attribute,PageId,Order,DestinationPageId")] Button button)
        {
            if (ModelState.IsValid)
            {
                _context.Add(button);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PageId"] = new SelectList(_context.Pages, "Id", "Title", button.PageId);
            return View(button);
        }

        // GET: Buttons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Buttons == null)
            {
                return NotFound();
            }

            var button = await _context.Buttons.FindAsync(id);
            if (button == null)
            {
                return NotFound();
            }
            ViewData["PageId"] = new SelectList(_context.Pages, "Id", "Title", button.PageId);
            return View(button);
        }

        // POST: Buttons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ButtonId,Text,Attribute,PageId,Order,DestinationPageId")] Button button)
        {
            if (id != button.ButtonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(button);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ButtonExists(button.ButtonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PageId"] = new SelectList(_context.Pages, "Id", "Title", button.PageId);
            return View(button);
        }

        // GET: Buttons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Buttons == null)
            {
                return NotFound();
            }

            var button = await _context.Buttons
                .Include(b => b.Page)
                .FirstOrDefaultAsync(m => m.ButtonId == id);
            if (button == null)
            {
                return NotFound();
            }

            return View(button);
        }

        // POST: Buttons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Buttons == null)
            {
                return Problem("Entity set 'MeranceaContext.Buttons'  is null.");
            }
            var button = await _context.Buttons.FindAsync(id);
            if (button != null)
            {
                _context.Buttons.Remove(button);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ButtonExists(int id)
        {
          return (_context.Buttons?.Any(e => e.ButtonId == id)).GetValueOrDefault();
        }
    }
}

Merancea/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Merancea.Data;
using Merancea.Models;

namespace Merancea.Controllers
{
    public class PagesController : Controller
    {
        private readonly MeranceaContext _context;

        public PagesController(MeranceaContext context)
        {
            _context = context;
        }

        // GET: Pages
        public async Task<IActionResult> Index()
        {
              return _context.Pages != null ? 
                          View(await _context.Pages.ToListAsync()) :
                          Problem("Entity set 'MeranceaContext.Pages'  is null.");
        }

        // GET: Pages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pages == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Pages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Content,CoverArt")] Page page)
        {
            if (ModelState.IsValid)
            {
                _context.Add(page);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Pages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pages == null)
            {
                return NotFound();
            }

            var page = await _context.Pages.Include(p => p.Buttons).FirstOrDefaultAsync(p => p.Id == id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Pages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Content,CoverArt")] Page page)
        {
            if (id != page.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(page);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Pages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pages == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // POST: Pages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pages == null)
            {
                return Problem("Entity set 'MeranceaContext.Pages'  is null.");
            }
            var page = await _context.Pages.FindAsync(id);
            if (page != null)
            {
                _context.Pages.Remove(page);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
          return (_context.Pages?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Merancea/Views/Shared/_FullPageLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <title>@ViewData["Title"] - Merancea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Merancea.styles.css" asp-append-version="true" />
</head>
<body>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<div class="top-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            <p class="text-success">
            &copy; 2022 - Merancea Final Project- <a asp-area="" asp-controller="Home" asp-action="AboutMe">GameDesigner</a>
                - <a href="https://www.linkedin.com/in/kasahi/" target="_blank">LinkedIn</a>
            </p>
        </div>
    </footer>
*@    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Merancea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <title>@ViewData["Title"] - Merancea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Merancea.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" 
                asp-area="" 
                asp-controller="Home" 
                asp-action="Index">Merancea</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pages" asp-action="Index">Table of Contents</a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Buttons" asp-action="Index">Buttons</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p class="text-success">
            &copy; 2022 - Merancea Final Project- <a asp-area="" asp-controller="Home" asp-action="AboutMe">GameDesigner</a>
                - <a href="https://www.linkedin.com/in/kasahi/" target="_blank">LinkedIn</a>
            </p>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>